Object {
  "exitCode": 1,
  "stderr": "",
  "stdout": "::debug::starting to run should fail
::error title=should fail,file=tests/example.mjs,line=5,col=3::AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:%0A%0A  assert(false)%0A%0A    at TestContext.<anonymous> (file://CWD/tests/example.mjs:5:3)%0A    at Test.runInAsyncScope (node:async_hooks:214:14)%0A    at Test.run (node:internal/test_runner/test:1047:25)%0A    at Test.start (node:internal/test_runner/test:944:17)%0A    at startSubtestAfterBootstrap (node:internal/test_runner/harness:296:17) {%0A  generatedMessage: true,%0A  code: 'ERR_ASSERTION',%0A  actual: false,%0A  expected: true,%0A  operator: '=='%0A}
::debug::starting to run should pass
::debug::completed running should pass
::group::Test results (1 passed, 1 failed)
::notice::Total Tests: 2%0ASuites 📂: 0%0APassed ✅: 1%0AFailed ❌: 1%0ACanceled 🚫: 0%0ASkipped ⏭️: 0%0ATodo 📝: 0%0ADuration 🕐: *ms
::endgroup::
",
}